### ISSUE TITLE
It doesn't work with Angular 13

### ISSUE THREAD

**Issue by scaljeri** [Nillcon248/auto-unsubscribe#2]
Hi

I was just testing with your decorator, and noticed that is does work with angular 12. Here is my test stackblitz: [test](https://stackblitz.com/edit/angular-ivy-t2vbtw?file=src%2Fapp%2Fapp.component.html)

However, if I do the same thing with angular 13 it doesn't work anymore: [demo](https://stackblitz.com/edit/angular-ivy-uptif6?file=src%2Fapp%2Fapp.component.html)

**Comment by nicosoca** [comment]
I also tested it and it does not work with angular 13, we need help!

**Comment by scaljeri** [comment]
I did a bit of searching and found [UntilDestroy](https://github.com/ngneat/until-destroy). It is a decorator which also seems to hook into the OnDestroy lifecycle hook

Which seems to work: [DEMO](https://stackblitz.com/edit/angular-ivy-drbdlg?file=src%2Fapp%2Fmozbaz%2Fmozbaz.component.ts)

So it is possible!!

**Comment by Nillcon248** [comment]
Hello, in depends on latest updates in my country I dropped out of IT, I am fixing it is soon as possible)

**Comment by Nillcon248** [comment]
Fixed, update the library)

**Comment by nicosoca** [comment]
Great :). What is the version we should use? 1.0.0 or 0.1.0?

**Comment by scaljeri** [comment]
Good work! I guess this version will only work for angular 13 right, so you might wanna add something like this to your package.json

        "peerDependencies": {
            "@angular/core": "^13.0.0"
        }

Not tested, but then you will not be able to use your lib with angular 12.

So, if it doesn't work with angular 12, I would go for 1.0.0, but if it is, 0,10 is fine.

**Comment by Nillcon248** [comment]
@nicosoca  The latest version is  0.1.0)

**Comment by scaljeri** [comment]
ok, so it will be, if backwards compatible,  0.1.1

**Comment by nicosoca** [comment]
I tried the initial @scaljeri example and it works for version 1.0.0 but it doesn't work for version 0.1.0.

**Comment by scaljeri** [comment]
ok, then you should use 1.0.0

**Comment by Nillcon248** [comment]
Oh guys, I apologize just forgot the latest version of this library is 1.0.0. So, now the latest version is [1.1.0](https://www.npmjs.com/package/ngx-auto-unsubscribe-decorator), it has backward compatibility with 12 angular and fixed the bug from the examples😊
